install.packages("brms")
install.packages("checkmate")
install.packages("cowplot")
install.packages("dplyr")
install.packages("forcats")
install.packages("ggdist")
install.packages("ggplot2")
install.packages("ggpp")
install.packages("glue")
install.packages("gridExtra")
install.packages("magrittr")
install.packages("photosynthesis")
install.packages("purrr")
install.packages("readr")
install.packages("stringr")
install.packages("tidybayes")
install.packages("tidyr")

install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))